#!/usr/bin/env python3
"""Generate a stand-in for the WPF XAML compiler's MainWindow.g.cs.

The real file is produced by PresentationBuildTasks, which only runs on Windows.
This reproduces the part the code-behind depends on — a field per x:Name and an
InitializeComponent — so the whole plugin can be type-checked on any platform.

As a side effect this also catches a class of bug the compiler otherwise finds
only on Windows: a control referenced in MainWindow.xaml.cs whose x:Name no
longer exists in the XAML, or whose element type changed underneath it.
"""

import os
import sys
import xml.etree.ElementTree as ET

XAML_NS = "{http://schemas.microsoft.com/winfx/2006/xaml}"

# Every element type that carries an x:Name in MainWindow.xaml.
WPF_TYPES = {
    "Window": "System.Windows.Window",
    "Grid": "System.Windows.Controls.Grid",
    "StackPanel": "System.Windows.Controls.StackPanel",
    "DockPanel": "System.Windows.Controls.DockPanel",
    "Border": "System.Windows.Controls.Border",
    "TextBlock": "System.Windows.Controls.TextBlock",
    "TextBox": "System.Windows.Controls.TextBox",
    "Button": "System.Windows.Controls.Button",
    "CheckBox": "System.Windows.Controls.CheckBox",
    "ComboBox": "System.Windows.Controls.ComboBox",
    "ComboBoxItem": "System.Windows.Controls.ComboBoxItem",
    "TabControl": "System.Windows.Controls.TabControl",
    "TabItem": "System.Windows.Controls.TabItem",
    "TreeView": "System.Windows.Controls.TreeView",
    "ProgressBar": "System.Windows.Controls.ProgressBar",
    "ScrollViewer": "System.Windows.Controls.ScrollViewer",
    "ListBox": "System.Windows.Controls.ListBox",
    "Slider": "System.Windows.Controls.Slider",
    "Label": "System.Windows.Controls.Label",
    "Expander": "System.Windows.Controls.Expander",
    # Project-local controls.
    "GanttView": "NavEx.Controls.GanttView",
}

HERE = os.path.dirname(os.path.abspath(__file__))
XAML = os.path.join(HERE, "..", "..", "NavEx", "MainWindow.xaml")
OUT_DIR = os.path.join(HERE, "obj")
OUT = os.path.join(OUT_DIR, "MainWindow.g.cs")


def main():
    root = ET.parse(XAML).getroot()

    named = []
    for element in root.iter():
        name = element.get(XAML_NS + "Name")
        if not name:
            continue
        tag = element.tag.split("}")[-1]
        if tag not in WPF_TYPES:
            print("error: no type mapping for <%s x:Name=\"%s\">; "
                  "add it to WPF_TYPES" % (tag, name), file=sys.stderr)
            return 1
        named.append((name, WPF_TYPES[tag]))

    fields = "\n".join("        internal %s %s;" % (t, n) for n, t in named)

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT, "w") as handle:
        handle.write(
            "// Generated by tools/typecheck/gen_xaml_stub.py — do not edit.\n"
            "// Stands in for the WPF XAML compiler output so the plugin can be\n"
            "// type-checked without Windows. Not used by the real build.\n"
            "namespace NavEx\n"
            "{\n"
            "    public partial class MainWindow : System.Windows.Window\n"
            "    {\n"
            "%s\n"
            "\n"
            "        public void InitializeComponent() { }\n"
            "    }\n"
            "}\n" % fields)

    print("generated %s with %d named controls" % (os.path.relpath(OUT), len(named)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
