"""Turn UBT's generated Definitions.h into the consumer-side equivalent.

UBT force-includes a ~160-line generated header when it compiles the SDK. Anything
linking against that SDK has to be compiled with the same configuration or the
headers describe a different binary layout than the DLL actually has. The only
difference for a consumer is direction: the SDK exports its API symbols, we import
them.
"""
import io
import re

SRC = r'D:\UE58src\Engine\Intermediate\Build\Win64\x64\DatasmithSDK\Development\DatasmithExporter\Definitions.h'
DST = r'native\NavExDatasmith\UEDefinitions.h'

src = io.open(SRC, encoding='utf-8-sig').read().replace('\r\n', '\n')

out = []
for line in src.split('\n'):
    # Symbol visibility flips: the SDK exported these, we import them.
    line = re.sub(r'(#define\s+\w*_API)\s+DLLEXPORT\s*$', r'\1 DLLIMPORT', line)
    line = re.sub(r'(#define\s+\w*_NON_ATTRIBUTED_API)\s+DLLEXPORT\s*$', r'\1 DLLIMPORT', line)

    # This names the module for logging; ours is not DatasmithExporter.
    if line.startswith('#define UE_MODULE_NAME'):
        line = '#define UE_MODULE_NAME "NavExDatasmith"'
    # We are a consumer, not an engine module.
    if line.startswith('#define UE_IS_ENGINE_MODULE'):
        line = '#define UE_IS_ENGINE_MODULE 0'

    if line.startswith('// Generated by UnrealBuildTool'):
        continue
    out.append(line)

header = '''// UE build configuration for anything compiled against the Datasmith SDK.
//
// GENERATED -- do not hand-edit. Regenerate with scratchpad/gen_defs.py from
//   <UE>\\Engine\\Intermediate\\Build\\Win64\\x64\\DatasmithSDK\\Development\\
//       DatasmithExporter\\Definitions.h
// after building the DatasmithSDK target, and only when changing engine version.
//
// UBT force-includes its own generated Definitions.h when it compiles the SDK
// (/FI, alongside /std:c++20). Unreal's headers are configuration-dependent --
// struct layout, alignment and inline behaviour all change with these macros --
// so a consumer compiled without them describes a different binary than the DLL
// it links against. Epic's published "Setting Up your Project" list predates UE5
// and is missing most of this, the *_NON_ATTRIBUTED_API family included.
//
// The only deliberate difference from UBT's copy: every *_API macro flips from
// DLLEXPORT to DLLIMPORT, because the SDK exports these symbols and we import
// them.
'''

io.open(DST, 'w', encoding='utf-8', newline='\r\n').write(header + '\n'.join(out))
print('wrote', DST, len(out), 'lines')
